US20016 Song Detail
crdschurch/crds-music pull request #211
Opened 2020-09-13 18:38 UTC by tcmacdonald

2020-09-13 20:38 UTC, silasbaur requested changes
3 Inline comments. Also the logo block is supposed to be on the /music jumbotron but it is no longer there

2020-09-13 20:38 UTC, silasbaur commented on _includes/_music-tabs.html
> -    <div class="search-panel music">
The class `music` was there for a reason. On the music page, the tabs are centered unlike the video page tabs.

2020-09-13 20:38 UTC, silasbaur commented on music/songs.html
> -              <a href="/albums/{{ song.album.slug }}">
When you click on the image of the album I would think it would go to the album page not the song page. When you get to mobile, the column with the album name goes away so now we do not have access to the album page

2020-09-13 20:38 UTC, silasbaur commented on music/songs.html
> +              <a href="{{ song.url }}">
This should go to the album page

2020-09-13 21:18 UTC, tcmacdonald commented on _includes/_music-tabs.html
> -    <div class="search-panel music">
Resolved in 5200a4c0abb9550804d2df185dc570619a02cb11 but I'm not happy about it. This is not a scalable design as the "center" position is ambiguous. The same element is handled differently on another page as the number of tabs increases. 

<img width="1282" alt="Crossroads_Music_and_Crossroads_Music" src="https://user-images.githubusercontent.com/50378/93028904-16f9b180-f5e5-11ea-8148-676903716809.png">

2020-09-13 21:18 UTC, tcmacdonald commented on music/songs.html
> -              <a href="/albums/{{ song.album.slug }}">
Thanks, fix in 5200a4c0abb9550804d2df185dc570619a02cb11

2020-09-13 21:18 UTC, tcmacdonald commented on music/songs.html
> +              <a href="{{ song.url }}">
5200a4c0abb9550804d2df185dc570619a02cb11

2020-09-13 21:20 UTC, tcmacdonald commented on _includes/_music-tabs.html
> -    <div class="search-panel music">
Honestly, on both pages, these tabs should be anchored to the right of the containing element on large screens, centered on small screens.

2020-09-14 00:56 UTC, silasbaur approved these changes

2020-09-14 00:56 UTC, merged