Song page logo defect
crdschurch/crds-music pull request #263
Opened 2020-10-14 13:02 UTC by kellgauthier

## Problem 
Logos were not in the correct location or inline on song detail page. 

## Solution 
Created video-search-header.scss that resolves column include.

2020-10-14 13:51 UTC, silasbaur requested changes
Looks good! Just some style fixes below:
1. At this screen size navigation is to close to the search bar
![Screen Shot 2020-10-14 at 9 48 01 AM](https://user-images.githubusercontent.com/32345656/95998073-7c1e0e00-0e02-11eb-9064-d955029a4288.png)
2. Search bar is too small at this screen size
![Screen Shot 2020-10-14 at 9 48 14 AM](https://user-images.githubusercontent.com/32345656/95998340-c43d3080-0e02-11eb-94c5-cf8690bc209b.png)

2020-10-14 19:15 UTC, dholloran-ample requested changes
@kellgauthier The arrows are semi-centered in the **sm** - **lg** (I guessing) sizes. See the screenshots below.

![screenshot 2020-10-14 at 15 05 30](https://user-images.githubusercontent.com/56852436/96034742-fe70f700-0e2f-11eb-94d8-a4aeb0b4aa92.png)

![screenshot 2020-10-14 at 15 05 49](https://user-images.githubusercontent.com/56852436/96034757-0466d800-0e30-11eb-9471-e427f37197f5.png)

2020-10-14 20:15 UTC, silasbaur submitted a review, later dismissed
Two inline comments and in this screenshot you can see that the arrow container is not centered.(look at the second screenshot to see the container not centered
![Screen Shot 2020-10-14 at 4 11 39 PM](https://user-images.githubusercontent.com/32345656/96040520-69bec700-0e38-11eb-84a3-d244d20b50ca.png)
![Screen Shot 2020-10-14 at 4 14 52 PM](https://user-images.githubusercontent.com/32345656/96040524-6cb9b780-0e38-11eb-93d2-facbf26b33eb.png)

2020-10-14 20:15 UTC, silasbaur commented on _assets/stylesheets/components/_video-search-header.scss
> +    @media (max-width: $screen-sm) {
Lets use min-width instead of max-width throughout this file

2020-10-14 20:15 UTC, silasbaur commented on _assets/stylesheets/components/_search-box.scss
> +
Remove extra line

2020-10-14 22:29 UTC, kellgauthier commented
@dholloran-ample and @silasbaur - thank you for the feedback. 

I went back and totally refactored the code, using bootstrap and min-width. Thanks for the help.

2020-10-15 13:46 UTC, silasbaur requested changes
One small inline comment and then you can merge this!

2020-10-15 13:46 UTC, silasbaur commented on _assets/stylesheets/components/_video-search-header.scss
> +    margin-top: 5px; text-align: center;
`text-align: center` needs to be on a new line

2020-10-15 14:13 UTC, merged